name       : plymouth
version    : 0.9.3
release    : 10
source     :
    - https://www.freedesktop.org/software/plymouth/releases/plymouth-0.9.3.tar.xz : 9f8dd08a90ceaf6228dcd8c27759adf18fc9482f15b6c56dcbcced268b4e4a74
license    : GPL-2.0
component  : system.boot
summary    : System boot screen
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(atk)
    - pkgconfig(libdrm)
    - docbook-xml
description: |
    Adds a splash screen during system startup
setup      : |
    %configure --enable-pango \
             --enable-gtk \
             --enable-drm \
             --enable-drm-renderer \
             --enable-systemd-integration \
             --enable-gdm-transition \
             --enable-pango \
             --libdir=/usr/lib \
             --without-system-root-install \
             --with-release-file=/etc/os-release \
             --with-background-start-color-stop=0x404552 \
             --with-background-end-color-stop=0x404552 \
             --with-logo=/usr/share/pixmaps/Solus.png
build      : |
    %make
install    : |
    %make_install
